services:
  antfields:
    image: antfields:demo
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/evb_dev/Albus/antfields-demo:/antfields
    gpus: all
    command: /bin/bash
