services:
  antfields-baseline:
    # image: antfields:demo
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=1,2
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/albusfang/Albus/antfields-demo-baseline:/antfields-demo-baseline
    # gpus: all
    runtime: nvidia
    command: /bin/bash
